### ISSUE TITLE
Category 조회 시  Todo도 함께 조회 하기

### ISSUE THREAD

**Issue by god1hyuk** [hanghae-w8-t4-plan-it/backend#48]
Category 조회 시 Todo 테이블을 Join 후 Todo도 함께 조회하여 List 타입으로 CategoryResponseDto에 담아 주어야 한다.

---

“success” : true,
“data” : [
	{
		“categoryId” : 1,
		“categoryName” : “운동”,
		“categoryColor” : “#000000”,
		“isPublic” : false,
		“categoryStatus” : “NON_STOP”,
		“todos” : [
			{
				“todoListId” : 1,
				“todoId” : 1,
				“title” : “달리기”,
				“memo” : “3km 구보”,
				“dueDate” : “2022-09-01”,
				“isAchieved” : false,
			},
			{
				“todoListId” : 1,
				“todoId” : 1,
				“title” : “턱걸이”,
				“memo” : “10개씩 3세트”,
				“dueDate” : “2022-09-01”,
				“isAchieved” : false,
			},
		],
	},
	{
		“categoryId” : 2,
		“categoryName” : “공부”,
		“categoryColor” : “#f3a2bc”,
		“isPublic” : false,
		“categoryStatus” : “NON_STOP”,
		“todos” : [
			{
				“todoListId” : 1,
				“todoId” : 1,
				“title” : “스프링 강의 시청”,
				“memo” : “주제 : JPA 연관관계”,
				“dueDate” : “2022-09-01”,
				“isAchieved” : false,
			},
			{
				“todoListId” : 1,
				“todoId” : 1,
				“title” : “SQL 강의 시청”,
				“memo” : “MySQL”,
				“dueDate” : “2022-09-01”,
				“isAchieved” : false,
			},
		],
	}
],
“error” : null

---

현재 Category와 Todo는 N : 1 단방향 연관관계를 맺고 있다.
단방향 관계이기에 Todo에서는 Category를 참조 하지만  Category에서는 Todo를 가지고 있지 않다.
그래서인지 Category에서 todo를 leftJoin 했을 때 join은 잘 된다.
하지만 todo를 List로 담을 수가 없다.

**Comment by ParkJong-ic** [comment]
해결 되셨나요?

**Comment by god1hyuk** [comment]
인프런의 김영한님 강의 질문란에 저와 같은 사례가 있었습니다. join을 해도 List안에 List로 한번에 담아낼 수 없다는 답변이 있었습니다. 완전히 불가능한 건지 확실히는 모르겠지만 일단 TodoList를 쿼리하여 Service단에서 반복하여 for문 내부에서 Todo를 쿼리하여 DTO에 담아내는 방식으로 처리하였습니다. 현재로써는 조회 속도가 나쁘지 않은 것 같습니다!
