### ISSUE TITLE
리프레시 토큰 재발급시 인증과 보안을 어떤 방식으로 하는게 좋을까요?

### ISSUE THREAD

**Issue by Jongleee** [hanghae-w8-t4-plan-it/backend#7]
저는 일단 프론트에서 이메일을 받는 방식을 생각하고 있습니다!

보안에서는 리프레시 토큰의 탈취에 대한 대비를 하고 싶습니다!

**Comment by ParkJong-ic** [comment]
자료를 찾아 보니 이메일도 안 받고 하는 게 좋긴 할 거 같은데 구현하기가 어려울 것 같습니다.

이메일이 고유값이라 그렇게 하는 방식이 좋을 거 같습니다.

아래 참고자료를 보시면 도움이 될 것 같습니다.

참고자료 : 
https://velog.io/@park2348190/JWT%EC%97%90%EC%84%9C-Refresh-Token%EC%9D%80-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80

https://youtu.be/y0xMXlOAfss

**Comment by Jongleee** [comment]
이메일->유저아이디를 활용하여 인증하는 방식으로 변경하여 완료하였습니다.
