### ISSUE TITLE
목표(카테고리) 종료 시 todo가 없는 날짜에 목표가 안 보이게 어떻게 구현해야 될까요?

### ISSUE THREAD

**Issue by ParkJong-ic** [hanghae-w8-t4-plan-it/backend#8]
1. 목표(카테고리)를 종료 했을 때 isEnd값을 true로 바꿔주고 todo가 있는지 확인해서 있다면 있는 곳만 카테고리를 보여주는 방식

2. isEnd값을 true로 바꿔줬을 때 그 데이터를 활용해서 프론트에서 안 보이게 하는 방식

이 부분에 대해서 코드를 어떻게 짜야될지 딱 생각이 안 드네요

**Comment by Jongleee** [comment]
프론트에서는 isEnd값이 true일때 안보이도록 하고, todo의 isAchieved 칼럼이 false인 todo가 있을때는 프론트에 전달하는 isEnd값을 다르게 보내주어 표시가 되도록하는 로직을 만들면 될 것 같습니다.
