### ISSUE TITLE
리포트 페이지에 필요한 데이터 조회

### ISSUE THREAD

**Issue by god1hyuk** [hanghae-w8-t4-plan-it/backend#87]
### n월의 리포트
1. n월 중 가장 많이 달성한 목표(카테고리)
- 가장 많이 달성한 카테고리 순 정렬
2. n월 중 가장 많이 달성한 날
- 달성률, 달성한 Todo 개수 중 판단 기준 논의 후 결정
3. n월 중 가장 집중한 날(ex. 2022년 9월 12일)
- 집중도(%) 데이터로 판단
4. n월 중 가장 집중이 잘되는 시간(ex. 15시 ~ 17시)
5. 100% 연속 달성 일수(ex. 3일)
- n월에 연속으로 100% 달성한 일수(combo)
6. n월의 총 좋아요 개수
7. n월 중 좋아요를 가장 많이 받은 날
8. n월에 좋아요를 가장 많이 누른 친구

**Comment by Jongleee** [comment]
3번의 경우에는 월기준으로 하면 전월과 이어지는 경우에 처리가 이상해지므로 이어지는 경우에만 전월과 이어지는 방식이면 될 것 같습니다.  나머지는 다 월을 기준으로 하면 될 것 같습니다

**Comment by Jongleee** [comment]
월의 리포트니까 전부 월단위로 통일시키는 것도 좋을것 같아요!

**Comment by god1hyuk** [comment]
@Jongleee 넵 확실히 통일성 있어서 좋네요!!
