### ISSUE TITLE
Todo의 D-Day 관련하여 테이블은 어떤 연관 관계를 가져야 할까?

### ISSUE THREAD

**Issue by god1hyuk** [hanghae-w8-t4-plan-it/backend#9]
- 요구 사항 :
1. todo 생성 시 클라이언트로 부터 요청 받은 날짜(dDay)로 비교하여 해당하는 todo가 없을 경우 todo_list를 생성
2.  todo_list(일별)기준으로 좋아요

- 질문 :
1. d_day 테이블 기준 todo_list 테이블과 (1:1) 식별키 연관관계
2. todo_list 기준 다중 PK(d_day 테이블 필요X)
3. d_day 테이블 기준으로 todo_list 테이블과(1:1), todo 테이블과(1:N) 연관관계

이 중 어떤 방식으로 데이터 구조를 설계해야 할까요?

**Comment by ParkJong-ic** [comment]
좀 전에 확인해보니 멘토님한테 질문한 답변이 와서 자료출처 올릴게요

https://www.notion.so/B-WIKI-46815ee6066442e5a8c71d0d635798ef

**Comment by god1hyuk** [comment]
복합키를 사용해야 할 정도의 상황이 아니라 판단되어 TodoList, Todo 테이블에 due_date를 각각 갖도록 처리하였습니다!
